version: '3.8'

services:
  frontend:
    build: ./frontend  # Path to frontend Dockerfile
    ports:
      - "3000:80"      # Map host port 3000 → container port 80 (NGINX)
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend   # Path to backend Dockerfile
    ports:
      - "8000:8000"    # Map host port 8000 → container port 8000 (FastAPI)
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/znexus
    depends_on:
      - db             # Wait for the database to start first

  db:
    image: postgres:14-alpine  # Use PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: znexus
    ports:
      - "5432:5432"    # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:       # Declare volume for PostgreSQL
